# Generated by Django 2.0.5 on 2018-06-05 02:00

import cliente.models
import core.utils
from django.db import migrations, models
import django.db.models.deletion
import pmoc.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('identificacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identificação')),
                ('ocupantes', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ocupantes Fixo/Flutuantes')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='Área em m²')),
                ('carga_termica', models.CharField(max_length=50, verbose_name='Carga Térmica BTU')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Ambientes',
                'verbose_name': 'Ambiente',
                'permissions': (('view_ambiente', 'Ver Ambiente'),),
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nome')),
                ('anexo', core.utils.ContentTypeRestrictedFileField(default='', storage=pmoc.storage_backends.PrivateMediaStorage(), upload_to=cliente.models.client_anexo_directory_path, verbose_name='Anexo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Anexos',
                'verbose_name': 'Anexo',
                'permissions': (('view_anexo', 'Ver anexos'),),
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Atividades',
                'verbose_name': 'Atividade',
                'permissions': (('view_atividade', 'Ver atividades'),),
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('razao_social', models.CharField(max_length=254, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('logradouro', models.CharField(blank=True, max_length=254, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=254, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=254, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=254, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('fone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes', to='empresa.Empresa', verbose_name='Empresa')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='clientes', to='empresa.UsuarioEmpresa')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'verbose_name': 'Cliente',
                'permissions': (('view_cliente', 'Ver cliente'),),
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('fabricante', models.CharField(blank=True, max_length=254, null=True, verbose_name='Fabricante')),
                ('identificacao', models.CharField(blank=True, max_length=254, null=True, verbose_name='Identificação')),
                ('capacidade', models.CharField(max_length=50, verbose_name='Capacidade Térmica BTU')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de instalação:')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data_desativado', models.DateField(blank=True, null=True, verbose_name='Data em que foi desativado?')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='cliente.Ambiente', verbose_name='Ambiente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='cliente.Cliente', verbose_name='Cliente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='empresa.EquipamentoGrupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name_plural': 'Equipamentos',
                'verbose_name': 'Equipamento',
                'permissions': (('view_equipamento', 'Ver equipamento'),),
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nome')),
                ('anexo', core.utils.ContentTypeRestrictedFileField(default='', storage=pmoc.storage_backends.PrivateMediaStorage(), upload_to=cliente.models.client_equipamento_directory_path, verbose_name='Anexo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anexos', to='cliente.Equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name_plural': 'Equipamento Anexos',
                'verbose_name': 'Equipamento Anexo',
                'permissions': (('view_equipamentoanexo', 'Ver anexos do equipamento'),),
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Medicoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_baixa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pressão Baixa')),
                ('pressao_alta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pressão Alta')),
                ('temperatura_insuflamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Temperatura de Insuflamento')),
                ('temperatura_retorno', models.CharField(blank=True, max_length=10, null=True, verbose_name='Temperatura de Retorno')),
                ('tensao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tensão')),
                ('corrente', models.CharField(blank=True, max_length=10, null=True, verbose_name='Corrente')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name_plural': 'Medições',
                'verbose_name': 'Medição',
                'permissions': (('view_medicoes', 'Ver Medições'),),
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=254, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operacoes', to='cliente.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Operações',
                'verbose_name': 'Operação',
                'permissions': (('view_operacao', 'Ver operações'),),
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OperacaoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=254, verbose_name='Grupo descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operacao_grupo', to='cliente.Cliente', verbose_name='Cliente')),
                ('equipamento_grupo', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='operacao_grupo', to='empresa.EquipamentoGrupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name_plural': 'Grupos de Operação',
                'verbose_name': 'Grupo de Operação',
                'permissions': (('view_operacaogrupo', 'Ver grupos de operação'),),
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroManutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista')),
                ('data_execucao', models.DateField(blank=True, null=True, verbose_name='Data da Execução')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manutencoes', to='cliente.Cliente', verbose_name='Cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manutencoes', to='cliente.Equipamento', verbose_name='Equipamento')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manutencoes', to='empresa.Tecnico', verbose_name='Técnico')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manutencoes', to='empresa.ManutencaoTipo', verbose_name='Tipo de Manutenção')),
            ],
            options={
                'verbose_name_plural': 'Registro de Manutenções',
                'verbose_name': 'Registro de Manutenção',
                'permissions': (('view_registromanutencao', 'Ver Registro de Manutenção'),),
                'ordering': ['data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='RegistroManutencaoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nome')),
                ('anexo', core.utils.ContentTypeRestrictedFileField(default='', storage=pmoc.storage_backends.PrivateMediaStorage(), upload_to=cliente.models.client_manutencao_directory_path, verbose_name='Anexo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('registro_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='cliente.RegistroManutencao', verbose_name='Registro de Manutencao')),
            ],
            options={
                'verbose_name_plural': 'Registro de Manutenção Anexos',
                'verbose_name': 'Registro de Manutenção Anexo',
                'permissions': (('view_registromanutencaoanexo', 'Ver anexos do registro de manuteção'),),
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='RegistroManutencaoOperacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manutencoes', to='cliente.Operacao', verbose_name='Operação')),
                ('registro_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='cliente.RegistroManutencao', verbose_name='Registro de Manutencao')),
            ],
            options={
                'verbose_name_plural': 'Registro de Manutenção Operações',
                'verbose_name': 'Regitro de Manutenção Operação',
                'permissions': (('view_registromanutencaooperacao', 'Ver Operações do Registro de Manutenção'),),
                'ordering': ['operacao__grupo__codigo', 'operacao__codigo'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome')),
                ('logradouro', models.CharField(blank=True, max_length=254, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=254, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=254, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=254, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('fone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidades', to='cliente.Cliente', verbose_name='Cliente')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidades', to='empresa.Responsavel', verbose_name='Responsável Técnico')),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'verbose_name': 'Unidade',
                'permissions': (('view_unidade', 'Ver unidade'),),
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='operacao',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operacoes', to='cliente.OperacaoGrupo', verbose_name='Grupo de Operação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='intervalo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operacoes', to='empresa.ManutencaoIntervalo', verbose_name='Intervalo entre manutenções'),
        ),
        migrations.AddField(
            model_name='medicoes',
            name='registro_manutencao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='cliente.RegistroManutencao', verbose_name='Registro de Manutencao'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atividades', to='cliente.Cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anexos', to='cliente.Cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ambientes', to='cliente.Atividade', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ambientes', to='cliente.Cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ambientes', to='cliente.Unidade', verbose_name='Unidade'),
        ),
    ]
